// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'bottom_bar_item_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class BottomBarItemBuilder extends _BottomBarItemBuilder {
  const BottomBarItemBuilder({required super.args});

  static const kType = 'bottom_bar_item';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static BottomBarItemBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) =>
      BottomBarItemBuilder(
        args: map,
      );
  @override
  BottomBarItemBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = BottomBarItemBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  BottomBarItem buildItem({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(
      childBuilder: childBuilder,
      data: data,
    );

    return BottomBarItem(
      activeItem: model.activeItem.build(
        childBuilder: childBuilder,
        context: context,
      ),
      inActiveItem: model.inActiveItem.build(
        childBuilder: childBuilder,
        context: context,
      ),
      itemLabel: model.itemLabel,
    );
  }
  
  @override
  Widget buildCustom({ChildWidgetBuilder? childBuilder, required BuildContext context, required JsonWidgetData data, Key? key}) {
    // TODO: implement buildCustom
    throw UnimplementedError();
  }
}

class JsonBottomBarItem extends JsonWidgetData {
  JsonBottomBarItem({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    required this.activeItem,
    required this.inActiveItem,
    this.itemLabel,
  }) : super(
          jsonWidgetArgs: BottomBarItemBuilderModel.fromDynamic(
            {
              'activeItem': activeItem,
              'inActiveItem': inActiveItem,
              'itemLabel': itemLabel,
              ...args,
            },
            args: args,
            registry: registry,
          ),
          jsonWidgetBuilder: () => BottomBarItemBuilder(
            args: BottomBarItemBuilderModel.fromDynamic(
              {
                'activeItem': activeItem,
                'inActiveItem': inActiveItem,
                'itemLabel': itemLabel,
                ...args,
              },
              args: args,
              registry: registry,
            ),
          ),
          jsonWidgetType: BottomBarItemBuilder.kType,
        );

  /* AUTOGENERATED FROM [BottomBarItem.activeItem]*/
  /// Un selected bottom bar item
  final JsonWidgetData activeItem;

  /* AUTOGENERATED FROM [BottomBarItem.inActiveItem]*/
  /// Selected bottom bar item
  final JsonWidgetData inActiveItem;

  /* AUTOGENERATED FROM [BottomBarItem.itemLabel]*/
  /// bottom bar item label
  final String? itemLabel;
}

class BottomBarItemBuilderModel extends JsonWidgetBuilderModel {
  const BottomBarItemBuilderModel(
    super.args, {
    required this.activeItem,
    required this.inActiveItem,
    this.itemLabel,
  });

  /* AUTOGENERATED FROM [BottomBarItem.activeItem]*/
  /// Un selected bottom bar item
  final JsonWidgetData activeItem;

  /* AUTOGENERATED FROM [BottomBarItem.inActiveItem]*/
  /// Selected bottom bar item
  final JsonWidgetData inActiveItem;

  /* AUTOGENERATED FROM [BottomBarItem.itemLabel]*/
  /// bottom bar item label
  final String? itemLabel;

  static BottomBarItemBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(
      map,
      args: args,
      registry: registry,
    );

    if (result == null) {
      throw Exception(
        '[BottomBarItemBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static BottomBarItemBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    BottomBarItemBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(
          map,
          normalize: true,
        );
      }

      if (map is BottomBarItemBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = BottomBarItemBuilderModel(
          args,
          activeItem: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['activeItem'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                  'Null value encountered for required parameter: [activeItem].');
            }
            return parsed;
          }(),
          inActiveItem: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['inActiveItem'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                  'Null value encountered for required parameter: [inActiveItem].');
            }
            return parsed;
          }(),
          itemLabel: map['itemLabel'],
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'activeItem': activeItem.toJson(),
      'inActiveItem': inActiveItem.toJson(),
      'itemLabel': itemLabel,
      ...args,
    });
  }
}

class BottomBarItemSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/gen_build/bottom_bar_item.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'BottomBarItem',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'activeItem': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'inActiveItem': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
      'itemLabel': SchemaHelper.stringSchema,
    },
  };
}
