name: Puppeteer Automation 2

on: 
  repository_dispatch:
    types: ['auto']

jobs:
  run-api-puppeteer:
    runs-on: ubuntu-latest
    outputs: 
      status: ${{ steps.result.outputs.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Predefine failure
        id: set-failure
        run: echo "status=failure" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies  
        run: |
          npm i
          
      - name: Run Puppeteer script
        id: run-script
        env:
            STACK_EMAIL: ${{ secrets.STACKOVERFLOW_EMAIL }}
            STACK_PASSWORD: ${{ secrets.STACKOVERFLOW_PASSWORD }}
        run: node index.js

      - name: Set success status
        if: success()
        run: echo "status=success" >> $GITHUB_ENV

      - name: Set job output
        id: result
        run: echo "status=${{ env.status }}" >> $GITHUB_OUTPUT

  display:
    needs: run-api-puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Show result
        run: echo "${{ needs.run-api-puppeteer.outputs.status }}"

  notify:
    needs: run-api-puppeteer
    uses: Dev21Maker/MAGitAPI/.github/workflows/main6.yml@main
    with:
      build_status: ${{ needs.run-api-puppeteer.outputs.status }}
    secrets: inherit
